---
title: Orion Publishing
description: custom imprint of Imad Pasha
locale: en
email: "imad.pasha@yale.edu"
url: https://orionpublishing.github.io  # the base hostname and protocol for your site, e.g. http://example.com
social:
  github: "prappleizer"
encoding: utf-8
# Theme Settings
logo: /img/logo.png
#rss: "/feed.xml"
remote_theme: 'erlzhang/jekyll-theme-persephone'
#theme: 'jekyll-theme-persephone'
theme_setting:
  blog_page: "blog/index.md"
  about_page: "about.md"
  archive_page: "archive.md"
  nav_pages:
    - "about.md"
    - "archive.md"
  lang:
    category_all: "Blog"
    blog_title: "Blog"
 #   comment:
 #     user: "昵称"
 #     email: "邮箱"
 #     url: "链接"
 #     message: "说点什么吧..."
 #     reply: "回复"

# Jekyll Settings
markdown: kramdown
kramdown:
    smart_quotes:  ["apos", "apos", "ldquo", "rdquo"]
permalink: /blog/:title:output_ext
timezone: America/New_York
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      keywords: writing, fantasy, creative fiction
      description: a blog to host my writing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      toc: true
plugins:
  #- jekyll-feed
  - jekyll-sitemap
  - jekyll-books
  #- jekyll-img-prefix
  #- jekyll-smiley
  #- jekyll-toc
  - jekyll-deploy-oss
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - scripts/
books_settings:
  ebook:
    enabled: true
    formats:
      - "mobi"
